# Generated by Django 4.0.5 on 2022-06-15 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='rate.project')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design', to='rate.project')),
                ('usability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usability', to='rate.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
